create table runways (id text not null,
                      airport_ref text,
                      airport_ident text,
                      length_ft text,
                      width_ft text,
                      surface text,
                      lighted text,
                      closed text,
                      le_ident text,
                      le_latitude_deg text,
                      le_longitude_deg text,
                      le_elevation_ft text,
                      le_heading_degT text,
                      le_displaced_threshold_ft text,
                      he_ident text,
                      he_latitude_deg text,
                      he_longitude_deg text,
                      he_elevation_ft text,
                      he_heading_degT text,
                      he_displaced_threshold_ft text,
                      primary key (id));
